# Generated by Django 5.2.3 on 2025-07-09 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Category", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="categories",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Home.category",
            ),
        ),
        migrations.DeleteModel(
            name="categories",
        ),
    ]
